# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# 1. Determinar si ninguno de los elementos es cero
a = np.array([1, 2, 3, 4])
no_ceros = np.all(a != 0)
print("Ningún elemento es cero:", no_ceros)

Ningún elemento es cero: True


In [3]:
# 2. Determinar si contiene algún elemento que no sea cero
a = np.array([0, 0, 2, 0])
alguno_no_cero = np.any(a != 0)
print("Contiene al menos un elemento que no es cero:", alguno_no_cero)

Contiene al menos un elemento que no es cero: True


In [4]:
# 3. Verificar si contiene valores infinitos o NaN
a = np.array([1, 2, np.nan, np.inf])
tiene_nan = np.isnan(a).any()
tiene_inf = np.isinf(a).any()
print("Contiene NaN:", tiene_nan)
print("Contiene infinitos:", tiene_inf)

Contiene NaN: True
Contiene infinitos: True


In [5]:
# 4. Determinar si contiene valores infinitos
a = np.array([1, 2, np.inf])
tiene_inf = np.isinf(a).any()
print("Contiene valores infinitos:", tiene_inf)

Contiene valores infinitos: True


In [6]:
# 5. Determinar si contiene valores NaN
a = np.array([1, np.nan, 3])
tiene_nan = np.isnan(a).any()
print("Contiene valores NaN:", tiene_nan)

Contiene valores NaN: True


In [7]:
# 6. Comparación elemento a elemento entre dos arreglos
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
mayor = a > b
mayor_o_igual = a >= b
menor = a < b
menor_o_igual = a <= b
print("a > b:", mayor)
print("a >= b:", mayor_o_igual)
print("a < b:", menor)
print("a <= b:", menor_o_igual)

a > b: [False False  True]
a >= b: [False  True  True]
a < b: [ True False False]
a <= b: [ True  True False]


In [8]:
# 7. Crear un arreglo y determinar la cantidad de memoria que ocupa
a = np.array([1, 7, 13, 105])
memoria = a.nbytes
print("Arreglo:", a)
print("Cantidad de memoria ocupada (bytes):", memoria)

Arreglo: [  1   7  13 105]
Cantidad de memoria ocupada (bytes): 16


In [9]:
# 8. Crear arreglos de ceros, unos y cincos
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10, 5)
print("Arreglo de ceros:", ceros)
print("Arreglo de unos:", unos)
print("Arreglo de cincos:", cincos)

Arreglo de ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Arreglo de unos: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Arreglo de cincos: [5 5 5 5 5 5 5 5 5 5]


In [10]:
# 9. Crear un arreglo con todos los números enteros entre 30 y 70
a = np.arange(30, 71)  # 71 para incluir el 70
print("Números enteros entre 30 y 70:", a)

Números enteros entre 30 y 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [11]:
# 10. Crear un arreglo con los números pares entre 30 y 70
a = np.arange(30, 71, 2)
print("Números pares entre 30 y 70:", a)

Números pares entre 30 y 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [12]:
# 11. Crear una matriz identidad de 3x3
identidad = np.eye(3)
print("Matriz identidad 3x3:\n", identidad)

Matriz identidad 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 12. Generar un número aleatorio entre 0 y 1
numero_aleatorio = np.random.rand()
print("Número aleatorio entre 0 y 1:", numero_aleatorio)

Número aleatorio entre 0 y 1: 0.6995321062133251


In [14]:
# 13. Crear un arreglo de 15 números aleatorios de una distribución normal estándar
arreglo_normal = np.random.randn(15)
print("Arreglo de 15 números aleatorios (distribución normal estándar):\n", arreglo_normal)

Arreglo de 15 números aleatorios (distribución normal estándar):
 [-1.65378537 -0.49873751  0.31254907 -0.62379042 -0.00489998 -0.65722708
 -1.79805908  0.1559437  -0.23754197 -0.78257091 -0.67409069  0.79913032
  1.36086976  0.79650925 -0.60393247]


In [15]:
# 14. Crear un arreglo con valores entre 15 y 55, e imprimir todos excepto el primero y el último
a = np.arange(15, 56)  # 56 para incluir el 55
print("Arreglo completo:", a)
print("Sin el primero y el último:", a[1:-1])

Arreglo completo: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Sin el primero y el último: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [16]:
# 15. Crear un vector de longitud 10 con valores equitativamente distribuidos entre 5 y 50
vector = np.linspace(5, 50, 10)
print("Vector equitativamente distribuido entre 5 y 50:", vector)

Vector equitativamente distribuido entre 5 y 50: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [17]:
# 16. Crear un vector con valores de 0 a 20 y cambiar el signo de los números de 9 a 15
vector = np.arange(0, 21)
print("Vector original:", vector)
vector[9:16] = -vector[9:16]
print("Vector modificado:", vector)

Vector original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Vector modificado: [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [18]:
# 17. Convertir un arreglo a una lista de Python
a = np.array([1, 2, 3])
lista = a.tolist()
print("Lista de Python:", lista)

Lista de Python: [1, 2, 3]


In [19]:
# 18. Convertir una lista de Python a un arreglo de Numpy
l = [1, 2, 3]
a = np.array(l)
print("Arreglo de Numpy:", a)

Arreglo de Numpy: [1 2 3]


In [20]:
# 19. Verificar qué números son pares en una matriz y almacenar los resultados en otra matriz
m = np.array([[1, 2], [3, 4]])
pares = (m % 2 == 0)
print("Matriz original:\n", m)
print("Matriz de pares (True si es par, False si es impar):\n", pares)

Matriz original:
 [[1 2]
 [3 4]]
Matriz de pares (True si es par, False si es impar):
 [[False  True]
 [False  True]]


In [21]:
# 20. Encontrar el número de filas y columnas de una matriz
m = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m.shape
print("Número de filas:", filas)
print("Número de columnas:", columnas)

Número de filas: 2
Número de columnas: 3
